[book]
authors = ["澪"]
language = "en"
multilingual = false
src = "src"
title = "The Chester Programming Language"

[preprocessor.gettext]
after = ["links"]

[build]
extra-watch-dirs = ["po"]

[output.html]
curly-quotes = true
additional-css = [
  "theme/css/language-picker.css",
]
additional-js = [
  "mode-chester.js",
  "editor.js",
]

[output.html.fold]
enable = true
level  = 1

[output.html.playpen]
editable = true
editor = "ace"
line-numbers = false