name: Build and Upload JARs

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up JDK
      uses: actions/setup-java@v2
      with:
        distribution: 'adopt'
        java-version: '17'

    - name: Cache SBT
      uses: actions/cache@v2
      with:
        path: |
          ~/.ivy2/cache
          ~/.sbt
          ~/.coursier
        key: ${{ runner.os }}-sbt-${{ hashFiles('**/*.sbt') }}
        restore-keys: |
          ${{ runner.os }}-sbt-

    - name: Build with SBT
      working-directory: chester-language-interpreter
      run: sbt clean assembly

    - name: Upload JAR files
      uses: actions/upload-artifact@v3
      with:
        name: assembly-jars
        path: |
          chester-language-interpreter/common/target/scala-*/common.jar
          chester-language-interpreter/interpreter/target/scala-*/interpreter.jar
          chester-language-interpreter/lsp/target/scala-*/lsp.jar
          chester-language-interpreter/repl/target/scala-*/repl.jar

    - name: Create GitHub Release
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.TOKEN }}
      with:
        tag_name: 'snapshot'
        release_name: 'Snapshot Release'
        draft: false
        prerelease: true

    - name: Upload Release Asset
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: chester-language-interpreter/common/target/scala-*/common.jar
        asset_name: common.jar
        asset_content_type: application/zip

    - name: Upload Release Asset
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: chester-language-interpreter/interpreter/target/scala-*/interpreter.jar
        asset_name: interpreter.jar
        asset_content_type: application/zip

    - name: Upload Release Asset
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: chester-language-interpreter/lsp/target/scala-*/lsp.jar
        asset_name: lsp.jar
        asset_content_type: application/zip

    - name: Upload Release Asset
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: chester-language-interpreter/repl/target/scala-*/repl.jar
        asset_name: repl.jar
        asset_content_type: application/zip
